# Generated by Django 3.2.3 on 2021-09-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclass', '0002_alter_onlineclass_teacher'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='onlineClasses',
            field=models.ManyToManyField(blank=True, to='onlineclass.OnlineClass'),
        ),
    ]
